### ISSUE TITLE
Migrate from NidukaAkalanka

### ISSUE THREAD

**Issue by POSTiGA1** [sudospaes/x-ui#13]
Hello,

Thank you for your release

Its possible to migrate from NidukaAkalanka to your x-ui ?

Regard's

**Comment by sudospaes** [comment]
Hello
Yeah you can migrate from NidukaAkalanka's x-ui.

First run this commands : 
```
mv /etc/x-ui-english /etc/x-ui
mv /etc/x-ui/x-ui-english.db /etc/x-ui/x-ui.db 
```
Now run install command :
```
bash <(curl -Ls https://raw.githubusercontent.com/sudospaes/x-ui/master/install.sh)
```

Good Luck

**Comment by sudospaes** [comment]
Hi
You have 3 ways to solve this problem:

**Solution 1 :** Delete and recreate the clients.

**Solution 2 :** Click the edit button for each inbound and just click the revise button without doing anything.

**Solution 3 :** From the system status section, click on the Switch Version option and select xray 1.7.5. Because the clients defined on the old xray are not supported by xray 1.8.
